[build]
builder = "nixpacks"
buildCommand = "npm run build:deploy"

[deploy]
startCommand = "npm install --prefix server && npm run start --prefix server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
